#!/usr/bin/env ruby
# frozen_string_literal: true

require 'redis_migrator'
require 'optparse'

RedisMigrator.configure do |config|

  OptionParser.new do |parser|
    parser.on('-c', '--concurrency[=WORKER_COUNT]', 'Number of workers', Integer) do |worker_count|
      config.worker_count = worker_count
    end
    parser.on('-s', '--source[=REDIS_SOURCE_URL]', 'Redis source connection string: redis://my-redis-host.example.com:6379, the redis instance data will be copied from.')
    parser.on('-t', '--target[=REDIS_TARGET_URL]', 'Redis connection string: redis://my-redis-host.example.com:6379, the redis instance data will be copied to.')
  end.parse!

end
